# Build this with the tag "ffbase".

ARG UBUNTU_VERSION=16.04
ARG MLNX_OFED_VERSION="4.0-2.0.0.1"

FROM ubuntu:${UBUNTU_VERSION}

WORKDIR /root

RUN apt-get update && apt-get -y upgrade

# Install necessary packages.
RUN apt-get -y install curl \
        lsb-release \
        git \
        build-essential \
        g++ \
        libnl-3-dev \
        libnl-route-3-dev

# Install RDMA drivers.
RUN "curl http://content.mellanox.com/ofed/MLNX_OFED-${MLNX_OFED_VERSION}/MLNX_OFED_LINUX-${MLNX_OFED_VERSION}-ubuntu${UBUNTU_VERSION}-x86_64.tgz | tar -xz"

RUN cd MLNX_OFED_LINUX-${MLNX_OFED_VERSION}-ubuntu${UBUNTU_VERSION}-x86_64 && echo "y" | ./mlnxofedinstall --user-space-only

RUN apt-get clean \
        && rm -rf /var/lib/apt/lists/*

# Copy over Freeflow files.
COPY . .

CMD ["/bin/bash"]
